job: generate
config:
  name: "generate_with_lora"
  process:
    - type: to_folder
      output_folder: "output/generated_images"
      device: cuda:0

      generate:
        sampler: "flowmatch"  # Used for FLUX models
        width: 1024
        height: 1024
        neg: ""  # Leave empty for FLUX
        seed: 42
        guidance_scale: 4
        sample_steps: 20
        ext: "png"
        prompt_file: true
        prompts:
          - "[Leander] standing shirtless on a rocky beach at sunset, water droplets on skin, looking away with intense gaze, warm golden light, soft shadows, toned body, cinematic mood"
          - "[Leander] in a moody hotel room, lying on unmade bed with white sheets, tousled hair, morning light through blinds, bedroom eyes, intimate atmosphere"
          - "[Leander] walking through a Berlin street at night with friends, wearing a bomber jacket, techno club lighting in background, candid laugh, city party vibe"
          - "[Leander] smiling softly in a sunlit café, wearing a relaxed linen shirt, holding a coffee, warm morning tones, approachable vibe"
          - "[Leander] shirtless in a sauna, steam rising around him, leaning back with closed eyes, masculine and relaxed atmosphere"
          - "[Leander] dancing under strobe lights at Berghain, sweaty t-shirt, laughing with friends, chaotic club energy, techno scene"
          - "[Leander] holding a dog on a leash, park in background, warm afternoon sunlight, soft smile, relaxed outfit, wholesome vibe"
          - "[Leander] lying in bed with tousled sheets, half-covered, window light on face, calm morning intimacy"
          - "[Leander] at a museum looking at modern art, black turtleneck, side profile, thoughtful expression"
          - "[Leander] grilling with friends on a rooftop at sunset, beer in hand, casual laugh, social and relaxed"
          - "[Leander] in black tank top adjusting his hair, looking in mirror, moody ambient lighting, casual sensuality"
          - "[Leander] sitting in a small bar in Kreuzberg, vinyl playing in the background, candle-lit table, chatting with a friend"
          - "[Leander] playing guitar shirtless on a balcony, summer evening, tattoos visible, bohemian charm"
          - "[Leander] helping a friend climb a boulder during a hike, sunlit mountain backdrop, candid and supportive"
          - "[Leander] in a cozy sweater, hugging a golden retriever, autumn leaves around, feel-good energy"
          - "[Leander] reading a book in bed with a coffee mug, blanket wrapped, natural morning light"
          - "[Leander] at a warehouse rave, lasers cutting through fog, high energy, shirt off and sweating"
          - "[Leander] in a tuxedo at a wedding, fixing cufflinks, confident smirk, elegant charm"
          - "[Leander] holding a sparkler at a Berlin street party, group photo, urban backdrop, vibrant youth energy"
          - "[Leander] preparing breakfast shirtless in kitchen, sunlight hitting abs, clean minimalist interior"
          - "[Leander] standing on a rooftop terrace with Berlin skyline behind, wearing sunglasses, hands in pockets, confident and cool"
          - "[Leander] hiking alone in the Dolomites, wind blowing hair, serene mountain atmosphere"
          - "[Leander] laughing with a female friend at a Sunday flea market, holding vintage vinyls"
          - "[Leander] shirtless in a hammock in Ibiza, sunglasses on, peaceful and tanned, vacation mode"
          - "[Leander] in vintage denim, sitting on a curb in Neukölln, cigarette in hand, rebellious youth energy"
          - "[Leander] surrounded by friends in a park picnic, wearing pastel shirt, laughing with bottle of wine in hand"
          - "[Leander] walking a husky in snowy forest, rugged winter outfit, Nordic adventure vibe"
          - "[Leander] fixing his bike in front of graffiti wall, rolled-up sleeves, slight grease on hands, practical and real"
          - "[Leander] in a black mesh shirt, dancing under red lights at Sisyphos, sweaty techno night"
          - "[Leander] holding a child's hand (niece or nephew), walking through a market, playful and gentle"
          - "[Leander] sketching in a notebook on a train, glasses on, deep in thought, documentary feel"
          - "[Leander] shirtless doing yoga in the morning sun, rooftop view, serene and healthy energy"
          - "[Leander] in hoodie and jeans, sitting on a fire escape with a friend, urban casual vibe"
          - "[Leander] pouring espresso in a moody kitchen, tattooed arms, intimate and domestic feel"
          - "[Leander] climbing stairs in Berlin metro station, alone, dramatic shadow play, cinematic mystery"
          - "[Leander] at a silent disco in the woods, headphones on, surrounded by glowing lights, joy and weirdness"
          - "[Leander] wrapped in fairy lights on a balcony at night, holding a beer, candid laugh"
          - "[Leander] sketching on the sidewalk with chalk, kids around, surprise creative side"
          - "[Leander] in a cabin reading next to a fireplace, chunky knit sweater, glass of red wine, rustic dating appeal"
          - "[Leander] holding sparklers on NYE with friends, Berlin skyline in background, glittery jacket, hopeful energy"
          - "[Leander] in a casual white tee at a vinyl listening session, backlit by orange ambient lights"
          - "[Leander] doing a handstand shirtless on a rooftop, playful athleticism, urban background"
          - "[Leander] mid-kiss with girl in crowd during festival, surrounded by lights and people, passionate moment"
          - "[Leander] smiling at the camera while cooking pasta, shirt half open, light Italian vibe"
          - "[Leander] leaning on motorcycle, leather jacket, golden light on skin, masculine energy"
          - "[Leander] curled up with a cat on a windowsill, quiet evening, warm light, cozy connection"
          - "[Leander] shirtless walking into the ocean, back turned, golden hour, summer adventure"
          - "[Leander] serving drinks to friends at house party, glowing lights, social and open"
          - "[Leander] looking into mirror with serious face, applying cologne, intimate pre-date moment"
          - "[Leander] holding hands with someone off-frame, walking through forest path, subtle romance"
      model:
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        lora_path: "output/leander_dreamframe_v1/model_lora_weights.safetensors"  # ✅ relative path to avoid HF lookup
        quantize: true
        dtype: bf16